/*
 * This source file was generated by the Gradle 'init' task
 */
package com.tomatohat;

import com.tomatohat.db.DatabaseManager;

import java.sql.*;

public class App {

    public static void main(String[] args) {

        DatabaseManager.getDatabaseManager();

    }
}
